name: stack-sims-cat latest

on: [push]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout stack-sims-cat
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: do docker build
        run: docker build --no-cache -t lsstdesc/stack-sims-cat:latest -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push
        run: docker push lsstdesc/stack-sims-cat:latest
       
